name: Docker Publish

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{inputs.go-version}}
          cache: true

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Run Tests
        run: go test -v -race -cover ./...

  docker-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-test
    outputs:
      image-tag: ${{ steps.vars.outputs.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Short Commit SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.27"
          cache: true

      - name: Run tests
        run: go test ./...

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build Docker image
        run: |
          docker build \
            -f ./Dockerfile \
            -t ghcr.io/${GITHUB_REPOSITORY,,}:latest \
            -t ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA} \
            .

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY,,}:latest
          docker push ghcr.io/${GITHUB_REPOSITORY,,}:${{ steps.vars.outputs.sha }}

  trigger-deployment:
    name: Trigger Deployment Dispatch
    needs: [lint-and-test, docker-publish]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Send repository_dispatch to Infra Repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          SERVICE_NAME: ${{ github.event.repository.name }}
          TARGET_REPO: "MorningBlossom/release"
          IMAGE_PATH: "ghcr.io/${{ github.repository }}"
          IMAGE_TAG: ${{ needs.docker-publish.outputs.image-tag }}
        run: |
          echo "Dispatching 'deploy-service' to $TARGET_REPO for $SERVICE_NAME with tag $IMAGE_TAG..."
          
          gh api "repos/$TARGET_REPO/dispatches" \
            -H "Accept: application/vnd.github+json" \
            -F "event_type=deploy-service" \
            -F "client_payload[service]=$SERVICE_NAME" \
            -F "client_payload[image]=$IMAGE_PATH" \
            -F "client_payload[tag]=$IMAGE_TAG"